# -*- coding: utf-8 -*-
"""Untitled24.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1DaoR1wCyx9ulxnOMA4FYypRftwWsLEqC
"""

gamma = 0.80
intensitymax = 255

def wavelengthtorgb(Wavelength):
  if (Wavelength >= 380) and (Wavelength < 440):
    Red = -(Wavelength - 440) / (440 - 380)
    Green = 0.0
    Blue = 1.0
  elif (Wavelength >= 440) and (Wavelength < 490):
    Red = 0.0
    Green = (Wavelength - 440) / (490 - 440);
    Blue = 1.0
  elif ((Wavelength >= 490) and (Wavelength < 510)):
    Red = 0.0
    Green = 1.0
    Blue = -(Wavelength - 510) / (510 - 490)

  elif ((Wavelength >= 510) and (Wavelength < 580)):
    Red = (Wavelength - 510) / (580 - 510)
    Green = 1.0
    Blue = 0.0
   
  elif ((Wavelength >= 580) and (Wavelength < 645)):
    Red = 1.0
    Green = -(Wavelength - 645) / (645 - 580)
    Blue = 0.0
    
  elif ((Wavelength >= 645) and (Wavelength < 781)):
    Red = 1.0
    Green = 0.0
    Blue = 0.0
  
  else: 
    Red = 0.0
    Green = 0.0
    Blue = 0.0

  if ((Wavelength >= 380) and (Wavelength < 420)):
    factor = 0.3 + 0.7 * (Wavelength - 380) / (420 - 380)

  elif ((Wavelength >= 420) and (Wavelength < 701)):
    factor = 1.0

  elif ((Wavelength >= 701) and (Wavelength < 781)):
    factor = 0.3 + 0.7 * (780 - Wavelength) / (780 - 700)
  else:
    factor = 0.0

  if Red == 0.0:
    redvalue=0
  else:
    redvalue=intensitymax * ((Red * factor)** gamma)
  if Green == 0.0:
    greenvalue=0
  else:
    greenvalue=intensitymax * ((Green * factor)** gamma)
  if Blue == 0.0:
    bluevalue=0
  else:
    bluevalue=intensitymax * ((Blue * factor)** gamma)

  nt=((Wavelength-380)/1000)+1.2

  return redvalue, greenvalue, bluevalue

with open("test5.txt","w") as f:
  for wave in range(35000,80000,1):
    r,g,b =wavelengthtorgb(wave/100)
    f.write(str(int(r))+' '+str(int(g))+' '+str(int(b))+'\r\n')

  #print(str(wave)+' '+str(int(r))+' '+str(int(g))+' '+str(int(b)))

